apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "news-article-crawler.fullname" . }}
  labels:
    {{- include "news-article-crawler.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cron.schedule }}"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cron.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "news-article-crawler.selectorLabels" . | nindent 12 }}
        spec:
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          serviceAccountName: {{ include "news-article-crawler.serviceAccountName" . }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.global.registry }}/{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          restartPolicy: Never
