image: docker:18.09.7

services:
  - docker:18.09.7-dind

stages:
  - build
  - deploy

default:
  before_script:
    - apk add make

frontend_build:
  stage: build
  script:
    - make -C services/frontend build
  only:
    changes:
      - services/frontend/**/*

