image: docker:18.09.7

services:
  - docker:18.09.7-dind


stages:
  - build
  - deploy

dev_build:
  stage: build
  script:
    - apk add make
    - make -C services/frontend build
  only:
    changes:
      - services/frontend/*

