analyticsMongodbPassword: pass123
analyticsMongodbRootPassword: abcd
analyticsMongoDbReplicaSetKey: abcd

newsArticlePostgresPassword: pass123
newsArticlePostgresPostgresPassword: abcd
newsArticlePostgresReplicationPassword: abcd
newsArticlePostgresLdapPassword: abcd

tweetPostgresPassword: pass123
tweetPostgresPostgresPassword: abcd
tweetPostgresReplicationPassword: abcd
tweetPostgresLdapPassword: abcd

tweetCrawlerPostgresPassword: pass123
tweetCrawlerPostgresPostgresPassword: abcd
tweetCrawlerPostgresReplicationPassword: abcd
tweetCrawlerPostgresLdapPassword: abcd

videoMongodbPassword: pass123
videoMongodbRootPassword: abcd
videoMongoDbReplicaSetKey: abcd

videoCrawlerPostgresPassword: pass123
videoCrawlerPostgresPostgresPassword: abcd
videoCrawlerPostgresReplicationPassword: abcd
videoCrawlerPostgresLdapPassword: abcd
