"""Added Job table

Revision ID: 5799f2922758
Revises: 
Create Date: 2020-03-16 16:39:02.681618

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5799f2922758'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('minTweetId', sa.String(), nullable=True),
    sa.Column('maxTweetId', sa.String(), nullable=True),
    sa.Column('politician', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Job')
    # ### end Alembic commands ###
