# Default values for word-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  wordCloud:
    repository: word-cloud
    pullPolicy: Always
  wordCloudAnalytic:
    repository: word-cloud-analytic
    pullPolicy: Always

nameOverride: word-cloud
fullnameOverride: word-cloud

service:
  type: ClusterIP
  port: 80

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

mongodb:
  mongodbPassword: pass123
  mongodbUsername: mongodb

  mongodbDatabase: admin

  nameOverride: word-cloud-mongodb

  fullnameOverride: word-cloud-mongodb

  ## Configure resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
#  resources:
#    requests:
#      memory: 64Mi
#      cpu: 60m
#    limits:
#      memory: 128Mi
#      cpu: 60m

nodeSelector: {}

tolerations: []

affinity: {}
