apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "word-cloud.fullname" . }}
  labels:
    {{- include "word-cloud.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "word-cloud.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "word-cloud.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.registry }}/{{ .Values.image.wordCloud.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.wordCloud.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
