apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: ScheduledSparkApplication
metadata:
  name: word-cloud-global-spark
  namespace: default
spec:
  schedule: "@every 4h"
  concurrencyPolicy: Allow
  template:
    type: Scala
    mode: cluster
    imagePullSecrets:
      - regcred
    image: "{{ .Values.global.registry }}/{{ .Values.image.wordCloudAnalytic.repository }}:{{ .Chart.AppVersion }}"
    imagePullPolicy: {{ .Values.image.wordCloudAnalytic.pullPolicy }}
    mainClass: GlobalWordCount
    mainApplicationFile: "local:///app/word-cloud-analytic.jar"
    sparkVersion: "2.4.5"
    restartPolicy:
      type: Never
    driver:
      cores: 1
      coreLimit: "1000m"
      memory: "512m"
      labels:
        version: 2.4.5
      serviceAccount: cluster-spark
    executor:
      coreRequest: "200m"
      coreLimit: "400m"
      instances: 2
      memory: "512m"
      labels:
        version: 2.4.5
