apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi
  namespace: default
spec:
  type: Scala
  mode: cluster
  imagePullSecrets:
    - regcred
  image: "{{ .Values.global.registry }}/{{ .Values.image.wordCloudAnalytic.repository }}:{{ .Chart.AppVersion }}"
  imagePullPolicy: {{ .Values.image.wordCloudAnalytic.pullPolicy }}
  mainClass: TweetWordCount
  mainApplicationFile: "local:///app/word-cloud-analytic.jar"
  sparkVersion: "2.4.5"
  restartPolicy:
    type: Never
  driver:
    cores: 1
    coreLimit: "1000m"
    memory: "512m"
    labels:
      version: 2.4.5
    serviceAccount: cluster-spark
  executor:
    coreRequest: "100m"
    coreLimit: "200m"
    instances: 1
    memory: "512m"
    labels:
      version: 2.4.5
