apiVersion: v1
kind: Secret
metadata:
  name: analytics-mongodb-secret
type: Opaque
data:
  mongodb-root-password: {{ randAlphaNum 10 | b64enc | quote }}
  mongodb-password: {{ .Values.analyticsMongodbPassword | b64enc | quote }}
  mongodb-replica-set-key: {{ randAlphaNum 10 | b64enc | quote }}
