apiVersion: v1
data:
  aws_access_key_id: {{ .Values.minioAccessKey | b64enc | quote }}
  aws_secret_access_key: {{ .Values.minioSecretKey | b64enc | quote }}
kind: Secret
metadata:
  name: kafka-connect-secret
type: Opaque
