apiVersion: v1
kind: Secret
metadata:
  name: news-article-crawler-postgres-secret
type: Opaque
data:
  postgresql-postgres-password: {{ .Values.newsArticleCrawlerPostgresPostgresPassword | b64enc | quote }}
  postgresql-password: {{ .Values.newsArticleCrawlerPostgresPassword | b64enc | quote }}
  postgresql-replication-password: {{ .Values.newsArticleCrawlerPostgresReplicationPassword | b64enc | quote }}
  postgresql-ldap-password: {{ .Values.newsArticleCrawlerPostgresLdapPassword | b64enc | quote }}
