apiVersion: v1
kind: Secret
metadata:
  name: news-article-postgres-secret
type: Opaque
data:
  postgresql-postgres-password: {{ .Values.newsArticlePostgresPostgresPassword | b64enc | quote }}
  postgresql-password: {{ .Values.newsArticlePostgresPassword | b64enc | quote }}
  postgresql-replication-password: {{ .Values.newsArticlePostgresReplicationPassword | b64enc | quote }}
  postgresql-ldap-password: {{ .Values.newsArticlePostgresLdapPassword | b64enc | quote }}
