apiVersion: v1
kind: Secret
metadata:
  name: state-party-affiliation-analytic-secret
type: Opaque
data:
  config.ini: |-
    {{ .Files.Get "static-files/state-party-affiliation-analytic-secret.ini" | b64enc }}
