apiVersion: v1
kind: Secret
metadata:
  name: tweet-mongodb-secret
type: Opaque
data:
  mongodb-root-password: {{ .Values.tweetMongodbRootPassword | b64enc | quote }}
  mongodb-password: {{ .Values.tweetMongodbPassword | b64enc | quote }}
  mongodb-replica-set-key: {{ .Values.tweetMongoDbReplicaSetKey | b64enc | quote }}
