apiVersion: v1
kind: Secret
metadata:
  name: tweet-crawler-postgres-secret
type: Opaque
data:
  postgresql-postgres-password: {{ .Values.tweetCrawlerPostgresPostgresPassword | b64enc | quote }}
  postgresql-password: {{ .Values.tweetCrawlerPostgresPassword | b64enc | quote }}
  postgresql-replication-password: {{ .Values.tweetCrawlerPostgresReplicationPassword | b64enc | quote }}
  postgresql-ldap-password: {{ .Values.tweetCrawlerPostgresLdapPassword | b64enc | quote }}
