apiVersion: v1
kind: Secret
metadata:
  name: video-crawler-postgres-secret
type: Opaque
data:
  postgresql-postgres-password: {{ .Values.videoCrawlerPostgresPostgresPassword | b64enc | quote }}
  postgresql-password: {{ .Values.videoCrawlerPostgresPassword | b64enc | quote }}
  postgresql-replication-password: {{ .Values.videoCrawlerPostgresReplicationPassword | b64enc | quote }}
  postgresql-ldap-password: {{ .Values.videoCrawlerPostgresLdapPassword | b64enc | quote }}
