apiVersion: v1
kind: Secret
metadata:
  name: video-mongodb-secret
type: Opaque
data:
  mongodb-root-password: {{ .Values.videoMongodbRootPassword | b64enc | quote }}
  mongodb-password: {{ .Values.videoMongodbPassword | b64enc | quote }}
  mongodb-replica-set-key: {{ .Values.videoMongoDbReplicaSetKey | b64enc | quote }}
