apiVersion: v1
kind: Secret
metadata:
  name: word-cloud-analytic-secret
type: Opaque
data:
  application.properties: |-
    {{ .Files.Get "static-files/word-cloud-analytic-secret.properties" | b64enc }}
