{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "politician.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - host: 35.231.193.61.xip.io
      http:
        paths:
          - backend:
              serviceName: {{ template "politician.fullname" . }}
              servicePort: {{ .Values.service.port }}
            path: /images
  {{- end }}
