clusterName: queue

kafka:
  resources:
    requests:
      memory: 64Mi
      cpu: 60m
    limits:
      memory: 64Mi
      cpu: 60m

zookeeper:
  resources:
    requests:
      memory: 64Mi
      cpu: 60m
    limits:
      memory: 64Mi
      cpu: 60m

sidecar:
  resources:
    requests:
      memory: 64Mi
      cpu: 60m
    limits:
      memory: 64Mi
      cpu: 60m