#apiVersion: kafka.strimzi.io/v1alpha1
#kind: KafkaConnector
#metadata:
#  name: s3-sink-connector
#  labels:
#    # The strimzi.io/cluster label identifies the KafkaConnect instance
#    # in which to create this connector. That KafkaConnect instance
#    # must have the strimzi.io/use-connector-resources annotation
#    # set to true.
#    strimzi.io/cluster: kafka-connect-cluster
#spec:
#  class: com.spredfast.kafka.connect.s3.sink.S3SinkConnector
#  tasksMax: 2
#  config:
#    tasks.max: 1,
#    topics: tweet-created,
#    s3.bucket.name: tweets,
#    s3.part.size: 5242880,
#    flush.size: 6,
#    store.url: http://minio:9000,
#    storage.class: io.confluent.connect.s3.storage.S3Storage,
#    format.class: io.confluent.connect.s3.format.json.JsonFormat,
#    partitioner.class: io.confluent.connect.storage.partitioner.DefaultPartitioner,
#    value.converter.schemas.enable: false
