apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
metadata:
  name: {{ .Values.clusterName }}
spec:
  kafka:
    version: 2.3.1
    replicas: 1
    listeners:
      plain: {}
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      log.message.format.version: "2.3"
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 8Gi
          deleteClaim: false
    resources:
        {{- toYaml .Values.kafka.resources | nindent 6 }}
    tlsSidecar:
      resources:
        {{- toYaml .Values.sidecar.resources | nindent 8 }}

  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 8Gi
      deleteClaim: false
    resources:
      {{- toYaml .Values.zookeeper.resources | nindent 6 }}
    tlsSidecar:
      resources:
        {{- toYaml .Values.sidecar.resources | nindent 8 }}
  entityOperator:
    topicOperator: {}
    userOperator: {}