apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  name: opinion
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
spec:
  partitions: 1
  replicas: 1
  config:
    retention.ms: 7200000
    segment.bytes: 1073741824