apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "state-party-affiliation-analytic.fullname" . }}
  labels:
    {{- include "state-party-affiliation-analytic.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cron.schedule }}"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 2
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cron.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "state-party-affiliation-analytic.selectorLabels" . | nindent 12 }}
        spec:
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          serviceAccountName: {{ include "state-party-affiliation-analytic.serviceAccountName" . }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.global.registry }}/{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              volumeMounts:
                - name: secret-volume
                  mountPath: /app/config.ini
                  subPath: config.ini
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          volumes:
            - name: secret-volume
              secret:
                secretName: state-party-affiliation-analytic-secret
          restartPolicy: Never
