apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "analytics.fullname" . }}
  labels:
    {{- include "analytics.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "analytics.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "analytics.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: regcred
      serviceAccountName: {{ include "analytics.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.global.registry }}/{{ .Values.image.analytic.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.analytic.pullPolicy }}
          volumeMounts:
            - name: secret-volume
              mountPath: /app/.env
              subPath: .env
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /politician-word-cloud/health
              port: http
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /politician-word-cloud/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: secret-volume
          secret:
            secretName: analytics-secret
