apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "tweet-crawler.fullname" . }}
  labels:
    {{- include "tweet-crawler.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.cron.schedule }}"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cron.backoffLimit }}
      template:
        metadata:
          labels:
            {{- include "tweet-crawler.selectorLabels" . | nindent 12 }}
        spec:
        {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          serviceAccountName: {{ include "tweet-crawler.serviceAccountName" . }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.global.registry }}/{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              volumeMounts:
                - name: secret-volume
                  mountPath: /app/config.ini
                  subPath: config.ini
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
          volumes:
            - name: secret-volume
              secret:
                secretName: tweet-crawler-secret
          restartPolicy: Never
