# Default values for tweet-crawler.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: tweet-crawler
  pullPolicy: Always

imagePullSecrets: [{name: "regcred"}]
nameOverride: tweet-crawler
fullnameOverride: tweet-crawler

cron:
  backoffLimit: 0
  schedule: "0 * * * *"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 100m
    memory: 128Mi

postgresql:

  nameOverride: tweet-crawler-postgresql


  fullnameOverride: tweet-crawler-postgresql

  ## PostgreSQL admin user
  ## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#setting-the-root-password-on-first-run
  postgresqlUsername: postgres

  ## PostgreSQL password
  ## ref: https://github.com/bitnami/bitnami-docker-postgresql/blob/master/README.md#setting-the-root-password-on-first-run
  ##
  postgresqlPassword: pass123

  ## Configure resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    requests:
      memory: 64Mi
      cpu: 60m
    limits:
      memory: 64Mi
      cpu: 60m


