# Default values for services.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


imagePullSecrets: []

politician:
  enabled: true

tweet:
  enabled: true

tweet-crawler:
  enabled: true

news-article:
  enabled: true

news-article-crawler:
  enabled: true

analytics:
  enabled: true

frontend:
  enabled: true

kafka:
  enabled: true

video:
  enabled: false

video-crawler:
  enabled: false

word-cloud-analytic:
  enabled: true

global:
  registry: registry.gitlab.com/brad_1357/polititrend
  host: somehost

