{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "frontend.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: {{ .Values.global.host }}
    http:
      paths:
        - backend:
            serviceName: {{ template "frontend.fullname" . }}
            servicePort: {{ .Values.service.port }}
          path: /
{{- end }}
