{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ template "frontend.fullname" . }}-ingress
spec:
  backend:
    serviceName: {{ template "frontend.fullname" . }}
    servicePort: {{ .Values.service.port }}
{{- end }}
